# Using a custom Node 6 image with the right dependencies.
image: spittet/futurospective-pipeline-container

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - yarn
          - npm run flow
          - npm run lint